import numpy as np

def cost_list_func():
    cost_list = np.array([
        "Park service bijdrage (PSB)",
        "Noodzakelijke werkzaamheden",
        "Administratiekosten",                      
        "Netbeheerkosten",
        "Verbruikstarieven GWE",
        "Voorschot GWE",
        "TV en internet",
        "Huisvuil",
        "Balkonschoonmaak",
        "Tuinonderhoud tot 400 m2",
        "Tuinonderhoud vanaf 400 m2",
        "CV",
        "Pelletkachel",
        "Onderhoud Boiler & Elektrische verwarming",
        "Warmtepomp",
        "Licentie en service ICY",
        "Videma (NL)/Unisono (BE)",
        "Ongediertebestrijding",
        "Schoonmaak buiten (buitenbekleding, ramen, terras en dakgoten) t/m 6p",
        "Schoonmaak buiten (buitenbekleding, ramen, terras en dakgoten) vanaf 7p",
        "Lease Brandblussers, CO melder en rookmelder inclusief jaarlijks onderhoud t/m 6p",
        "Lease Brandblussers, CO melder en rookmelder inclusief jaarlijks onderhoud vanaf 7p",
        "Legionellapreventie (niet separaat af te nemen)",
        "Eindschoonmaak na eigen gebruik eigenaar t/m 6p",
        "Eindschoonmaak na eigen gebruik eigenaar vanaf 7p",
        "Huur brievenbus",
        "Parkeergeld extra auto",
        "Huisdier",
        "Onderhoud sauna, hot tub",
        "Onderhoudscontract voor de airco (excl. eventuele reparaties) 1 x per jaar voor 1 airco",
        "Onderhoudscontract voor de airco (excl. eventuele reparaties) 1 x per jaar voor 2 airco's",
        "2 x per jaar zonnepanelen (max 8 stuks) schoonmaken met osmose water per dak",
        "1 x per maand glasbewassing buitenzijde alle ramen",
        "1 x per kwartaal glasbewassing buitenzijde alle ramen",
        "1 x per jaar schoorsteenvegen per schoorsteen",
        "Sedumdak onderhoud, 2 x per jaar",
        "Extra 1",
        "Extra 2",
        "Extra 3",
        "Extra 4",
        "Extra 5",
    ])
    return cost_list

def park_cost_list_func():
    park_cost_list = np.array([
        "Administratiekosten",
        "Annuleerverzekering",
        "Schoonmaak",
        "Voorkeursboeking",
        "Huisdier(en)",
        "Toeristenbelasting",
        "Lakenpakket",
        "Handdoekenpakket",
        "Early in-check"
        "Laat vertrek",
        "Additionele guest-services 1",
        "Additionele guest-services 2",
        "Additionele guest-services 3",
        "Additionele guest-services 4",
        "Additionele guest-services 5",
        "Extra 1",
        "Extra 2",
        "Extra 3",
        "Extra 4",
        "Extra 5",
    ])
    return park_cost_list